Class {
	#name : #FkDataPipelinePerformance2024Show,
	#superclass : #Object,
	#traits : 'TGtSlideShow',
	#classTraits : 'TGtSlideShow classTrait',
	#category : #FeenkMoldableDevelopmentGOTO2024Show
}

{ #category : #'as yet unclassified' }
FkDataPipelinePerformance2024Show >> slide001Pipeline01: aSlide [
	<gtSlide>
	^ aSlide filePicture
		priority: 1;
		fileReference: (GtResourcesUtility resourceAtPath: 'feenkcom/feenk-stories/res/pipeline-1.png')
]

{ #category : #'as yet unclassified' }
FkDataPipelinePerformance2024Show >> slide002Pipeline01: aSlide [
	<gtSlide>
	^ aSlide filePicture
		priority: 2;
		fileReference: (GtResourcesUtility resourceAtPath: 'feenkcom/feenk-stories/res/pipeline-2.png')
]

{ #category : #'as yet unclassified' }
FkDataPipelinePerformance2024Show >> slide003Pipeline01: aSlide [
	<gtSlide>
	^ aSlide filePicture
		priority: 3;
		fileReference: (GtResourcesUtility resourceAtPath: 'feenkcom/feenk-stories/res/pipeline-3.png')
]

{ #category : #'as yet unclassified' }
FkDataPipelinePerformance2024Show >> slide004Pipeline01: aSlide [
	"<gtSlide>"
	^ aSlide filePicture
		priority: 4;
		fileReference: (GtResourcesUtility resourceAtPath: 'feenkcom/feenk-stories/res/pipeline-4.png')
]

{ #category : #'as yet unclassified' }
FkDataPipelinePerformance2024Show >> slide005Pipeline01: aSlide [
	<gtSlide>
	^ aSlide filePicture
		priority: 5;
		fileReference: (GtResourcesUtility resourceAtPath: 'feenkcom/feenk-stories/res/pipeline-5.png')
]

{ #category : #'as yet unclassified' }
FkDataPipelinePerformance2024Show >> slide006Pipeline01: aSlide [
	<gtSlide>
	^ aSlide filePicture
		priority: 6;
		fileReference: (GtResourcesUtility resourceAtPath: 'feenkcom/feenk-stories/res/pipeline-6.png')
]

{ #category : #'as yet unclassified' }
FkDataPipelinePerformance2024Show >> slide007Pipeline01: aSlide [
	<gtSlide>
	^ aSlide filePicture
		priority: 7;
		fileReference: (GtResourcesUtility resourceAtPath: 'feenkcom/feenk-stories/res/pipeline-7.png')
]
