Class {
	#name : #FkDataPipelinePerformance2024Show,
	#superclass : #Object,
	#traits : 'TGtSlideShow',
	#classTraits : 'TGtSlideShow classTrait',
	#category : #FeenkMoldableDevelopmentGOTO2024Show
}

{ #category : #'as yet unclassified' }
FkDataPipelinePerformance2024Show >> slide001Pipeline01: aSlide [
	<gtSlide>
	^ aSlide filePicture
		priority: 1;
		maxScale: 1;
		fileReference: (GtResourcesUtility resourceAtPath: 'feenkcom/feenk-stories/res/pipeline-1.png')
]

{ #category : #'as yet unclassified' }
FkDataPipelinePerformance2024Show >> slide002Pipeline02: aSlide [
	<gtSlide>
	^ aSlide filePicture
		priority: 2;
		maxScale: 1;
		fileReference: (GtResourcesUtility resourceAtPath: 'feenkcom/feenk-stories/res/pipeline-2.png')
]

{ #category : #'as yet unclassified' }
FkDataPipelinePerformance2024Show >> slide003Pipeline03: aSlide [
	<gtSlide>
	^ aSlide filePicture
		priority: 3;
		maxScale: 1;
		fileReference: (GtResourcesUtility resourceAtPath: 'feenkcom/feenk-stories/res/pipeline-3.png')
]

{ #category : #'as yet unclassified' }
FkDataPipelinePerformance2024Show >> slide004Pipeline01: aSlide [
	"<gtSlide>"
	^ aSlide filePicture
		priority: 4;
		fileReference: (GtResourcesUtility resourceAtPath: 'feenkcom/feenk-stories/res/pipeline-4.png')
]

{ #category : #'as yet unclassified' }
FkDataPipelinePerformance2024Show >> slide005Pipeline05: aSlide [
	<gtSlide>
	^ aSlide filePicture
		priority: 5;
		maxScale: 1;
		fileReference: (GtResourcesUtility resourceAtPath: 'feenkcom/feenk-stories/res/pipeline-5.png')
]

{ #category : #'as yet unclassified' }
FkDataPipelinePerformance2024Show >> slide006Pipeline06: aSlide [
	<gtSlide>
	^ aSlide filePicture
		priority: 6;
		maxScale: 1;
		fileReference: (GtResourcesUtility resourceAtPath: 'feenkcom/feenk-stories/res/pipeline-6.png')
]

{ #category : #'as yet unclassified' }
FkDataPipelinePerformance2024Show >> slide007Pipeline07: aSlide [
	<gtSlide>
	^ aSlide filePicture
		priority: 7;
		maxScale: 1;
		fileReference: (GtResourcesUtility resourceAtPath: 'feenkcom/feenk-stories/res/pipeline-7.png')
]
