Class {
	#name : #FkDbMigrationCraftConf2024Show,
	#superclass : #Object,
	#traits : 'TGtSlideShow',
	#classTraits : 'TGtSlideShow classTrait',
	#category : #FeenkMoldableDevelopmentCraftConf2024
}

{ #category : #accessing }
FkDbMigrationCraftConf2024Show >> slide001DbMigration01: aSlide [
	<gtSlide>
	^ aSlide filePicture
		priority: 1;
		fileReference: (GtResourcesUtility resourceAtPath: 'feenkcom/feenk-stories/res/db-migration-1.png')
]

{ #category : #accessing }
FkDbMigrationCraftConf2024Show >> slide002DbMigration02: aSlide [
	<gtSlide>
	^ aSlide filePicture
		priority: 2;
		fileReference: (GtResourcesUtility resourceAtPath: 'feenkcom/feenk-stories/res/db-migration-2.png')
]

{ #category : #accessing }
FkDbMigrationCraftConf2024Show >> slide003DbMigration03: aSlide [
	<gtSlide>
	^ aSlide filePicture
		priority: 3;
		fileReference: (GtResourcesUtility resourceAtPath: 'feenkcom/feenk-stories/res/db-migration-3.png')
]

{ #category : #accessing }
FkDbMigrationCraftConf2024Show >> slide004DbMigration04: aSlide [
	<gtSlide>
	^ aSlide filePicture
		priority: 4;
		fileReference: (GtResourcesUtility resourceAtPath: 'feenkcom/feenk-stories/res/db-migration-4.png')
]

{ #category : #accessing }
FkDbMigrationCraftConf2024Show >> slide005DbMigration05: aSlide [
	<gtSlide>
	^ aSlide filePicture
		priority: 5;
		fileReference: (GtResourcesUtility resourceAtPath: 'feenkcom/feenk-stories/res/db-migration-5.png')
]

{ #category : #accessing }
FkDbMigrationCraftConf2024Show >> slide006DbMigration06: aSlide [
	<gtSlide>
	^ aSlide filePicture
		priority: 6;
		fileReference: (GtResourcesUtility resourceAtPath: 'feenkcom/feenk-stories/res/db-migration-6.png')
]
